PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/b89737395b8a6ff96ac21991cbb4b9012a2bc972

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/a96d05c286fc1c619111f220e500b14e18c0509c) in current PX4/master (e9e9556130763aa91f593c3f2ef4bbcfa511c8e9)
https://github.com/PX4/NuttX/compare/a96d05c286fc1c619111f220e500b14e18c0509c...b89737395b8a6ff96ac21991cbb4b9012a2bc972

b89737395b (HEAD, origin/master) vfs/epoll: add epoll_create1(2) implement
2e2ebb95ca sys/poll/epoll: sync the epoll_event struct layout with pollfd
155860ad15 sys/epoll: move the private handle to epoll_data_t
f97b8436b3 drivers/bch: flush the dirty sector to keep the sector sequence
ed3cddb684 drivers/bch: delay the sector flush
e5f6dafe1f net/socket: add SOCK_CLOEXEC/SOCK_NONBLOCK support
07ce0deda0 Fix Added options for I-Cache & D-Cache broken on c101076704
d43bf7717e sched: Support config the argument passed to init
7ce2b3fa74 libc/pthread: Implement pthread_condattr_[g|s]etclock
79d476e423 Fix libsupc++.a(vterminate.o): undefined reference to `_impure_ptr'

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/18158ed271ceaa0a379707d7d3e94fc8077a59ac

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/95e105548a2037f42bf2f13b214ae083b921ff03) in current PX4/master (e9e9556130763aa91f593c3f2ef4bbcfa511c8e9)
https://github.com/PX4/NuttX-apps/compare/95e105548a2037f42bf2f13b214ae083b921ff03...18158ed271ceaa0a379707d7d3e94fc8077a59ac

18158ed2 (HEAD -> master, origin/master) system: add libuv port for NuttX
74c506b4 nsh: Don't check CONFIG_NFILE_STREAMS for mkdir/rename/rmdir/fs_unlink
e71e537e ftpc_transfer.c:667:15: Fix error: ‘argc’ undeclared
aaa198f0 interpreters/duktape: Clean objects
08c59984 graphics/lvgl: Specific LVGL version by kconfig
7099bc4b interpreters/duktape: Add console/print/alart support
efeb1d10 netutils/ftpc: Change watchdog callback prototype
fcd3937d system/cu: refactor, add option -c to disable \n -> \r\n conversion
ebf37162 Fix nxstyle warning
bf4c36c8 netutils/ftpc: Embed wdog_s in ftpc_session_s directly